[package]
name = "dodrio"
version = "0.1.0"
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
edition = "2018"

[dependencies]
bumpalo = "2.1.0"
cfg-if = "0.1.6"
futures = "0.1.25"
wasm-bindgen = "0.2.37"
wasm-bindgen-futures = "0.3.14"
js-sys = "0.3.14"
log = { version = "0.4.6", optional = true }

[dependencies.web-sys]
version = "0.3.14"
features = [
  "console",
  "Document",
  "Element",
  "Event",
  "Node",
  "Window",
]

[dev-dependencies]
console_log = "0.1.2"
dodrio-js-api = { version = "=0.1.0", path = "./crates/js-api" }
log = "0.4.6"
wasm-bindgen-test = "0.2.37"

[dev-dependencies.web-sys]
version = "0.3.14"
features = [
  "Attr",
  "EventTarget",
  "HtmlElement",
  "NamedNodeMap",
  "NodeList",
]

[profile.release]
incremental = false
lto = true
opt-level = "s"

[workspace]
members = [
  "./crates/js-api",
  "./examples/counter",
  "./examples/hello-world",
  "./examples/input-form",
  "./examples/js-component",
  "./examples/moire",
  "./examples/todomvc",
]
